# Generated by Django 3.0.6 on 2020-05-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_title', models.CharField(max_length=200)),
                ('Card_content', models.TextField()),
                ('Card_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
